"""change duration Time  to String 

Revision ID: 317362392117
Revises: a67225ba4be0
Create Date: 2026-07-25 21:26:47.055398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317362392117'
down_revision = 'a67225ba4be0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.TIME(),
               type_=sa.String(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.alter_column('duration',
               existing_type=sa.String(),
               type_=sa.TIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
